# Generated by Django 5.0.4 on 2024-05-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parcel_id', models.IntegerField(max_length=30)),
                ('mobile_number', models.IntegerField(max_length=10)),
                ('status', models.TextField(max_length=30)),
            ],
        ),
    ]
