# Generated by Django 5.0.4 on 2024-05-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='mobile_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='parcel_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(max_length=30),
        ),
    ]
